/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A2UISurface: typeof import('./src/components/chat/A2UISurface.vue')['default']
    AgentStatusIndicator: typeof import('./src/components/chat/AgentStatusIndicator.vue')['default']
    AgentWorkingIndicator: typeof import('./src/components/chat/AgentWorkingIndicator.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    AppNavigationRail: typeof import('./src/components/AppNavigationRail.vue')['default']
    AppSettingsMenu: typeof import('./src/components/AppSettingsMenu.vue')['default']
    AudioRecorder: typeof import('./src/components/ContentInput/AudioRecorder.vue')['default']
    ChatBubble: typeof import('./src/components/chat/ChatBubble.vue')['default']
    ChatFilePart: typeof import('./src/components/chat/ChatFilePart.vue')['default']
    ChatTextContent: typeof import('./src/components/chat/ChatTextContent.vue')['default']
    ChatToolCallPanel: typeof import('./src/components/chat/ChatToolCallPanel.vue')['default']
    ContentInput: typeof import('./src/components/ContentInput/ContentInput.vue')['default']
    ExpirationTimer: typeof import('./src/components/chat/ExpirationTimer.vue')['default']
    FileUploader: typeof import('./src/components/ContentInput/FileUploader.vue')['default']
    JsonTreeNode: typeof import('./src/pages/threads/components/JsonTreeNode.vue')['default']
    ProfileMenu: typeof import('./src/components/ProfileMenu.vue')['default']
    RichTextInput: typeof import('./src/components/ContentInput/RichTextInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreadComposerCard: typeof import('./src/pages/threads/components/ThreadComposerCard.vue')['default']
    ThreadMessageDebugDialog: typeof import('./src/pages/threads/components/ThreadMessageDebugDialog.vue')['default']
    ThreadMessageDetailsDialog: typeof import('./src/pages/threads/components/ThreadMessageDetailsDialog.vue')['default']
    ToolBatchChecklist: typeof import('./src/components/chat/ToolBatchChecklist.vue')['default']
    ToolBatchRow: typeof import('./src/components/chat/ToolBatchRow.vue')['default']
    ToolInterruptResolver: typeof import('./src/components/chat/ToolInterruptResolver.vue')['default']
    ToolPermissionCard: typeof import('./src/components/chat/ToolPermissionCard.vue')['default']
  }
}
